#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Installs vim-anywhere. Intended for use via curl:
#
#   $ curl -fsSL https://raw.github.com/b3s1r/vim-anywhere/master/install | bash

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

err() { echo -e "$@" 1>&2; }

check_installed() { hash $1 &> /dev/null; }

require_installed() {
  if ! check_installed $1; then
    err "vim-anywhere requires $1 to function"
    if [[ "$2" != "" ]]; then echo $2; fi
    exit 1
  fi
}

require_one_installed() {
  for file in $*; do
    check_installed $file && return
  done
  err "vim-anywhere requires one of the following to be installed:\n$*"
  exit 1
}

AW_PATH=$HOME/.vim-anywhere
AW_URL='https://github.com/b3s1r/vim-anywhere'

###
# pre-installation checks
###

# Check if vim-anywhere is already installed. If so, remove the previous
# installation.
if [ -a $AW_PATH ]; then
  echo 'Cleaning up previous installation...'
  rm -rf $AW_PATH
  # TODO: It would be nice to have an option for user input here
  # Reinstall vim-anywhere (y/n)? ... or something like that
fi

require_installed git

# if we are in a git repo, unset env vars
if git rev-parse --git-dir &> /dev/null; then
  unset $(git rev-parse --local-env-vars) &> /dev/null
fi

# Linux specific checks
if [[ $OSTYPE == "linux-gnu" ]]; then
  require_installed xclip

# Unsupported OS
else
  echo "OS '$OSTYPE' is not supported!"
  exit 1
fi

###
# installation
###

echo "Installing vim-anywhere..."

git clone $AW_URL $AW_PATH


echo "vim-anywhere has been successfully installed!"
echo "To use it, add $AW_PATH/bin/run to your PATH and configue a Keybinding un your window manager"
