#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Uninstalls vim-anywhere

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

check_installed() { hash $1 &> /dev/null; }

AW_PATH=$HOME/.vim-anywhere
DOC_PATH=/tmp/vim-anywhere

###
# uninstall
###

rm -rf $AW_PATH $DOC_PATH

echo "vim-anywhere has been successfully uninstalled!"
